import assert from 'node:assert/strict';
import { describe, it } from 'node:test';
import { createInstrumentRegistry } from './instrumentRegistry';
import { renderGrandPianoVoice, renderRhodesVoice, renderOrganVoice, renderPluckedGuitarVoice, renderStringsVoice, renderPizzicatoVoice, renderBrassVoice, renderMarimbaVoice } from './instruments/legacyAcoustic';
import { renderAcid303Voice, renderReeseBassVoice, render808SubVoice, renderSupersawVoice, renderAmbientPadVoice, renderVoxChoirVoice, renderChiptuneVoice } from './instruments/legacySynth';
import { renderLegacyDrumVoice } from './instruments/legacyDrum';

class FakeParam { value = 0; setValueAtTime(v:number){this.value=v;} linearRampToValueAtTime(v:number){this.value=v;} exponentialRampToValueAtTime(v:number){this.value=v;} cancelScheduledValues(){} }
class FakeNode { readonly gain=new FakeParam(); readonly frequency=new FakeParam(); readonly detune=new FakeParam(); readonly playbackRate=new FakeParam(); readonly pan=new FakeParam(); type='sine'; Q=new FakeParam(); buffer:any=null; startCalls=0; stopCalls=0; connect(){} start(){this.startCalls++;} stop(){this.stopCalls++;} }
class FakeBuffer { readonly data:Float32Array; constructor(public readonly duration=1,public readonly sampleRate=44100){this.data=new Float32Array(Math.max(1,Math.floor(duration*sampleRate)));} getChannelData(){return this.data;} }
class FakeContext { currentTime=0; sampleRate=44100; readonly nodes:FakeNode[]=[]; createOscillator(){const n=new FakeNode();this.nodes.push(n);return n as any;} createGain(){const n=new FakeNode();this.nodes.push(n);return n as any;} createBiquadFilter(){const n=new FakeNode();this.nodes.push(n);return n as any;} createBufferSource(){const n=new FakeNode();this.nodes.push(n);return n as any;} createBuffer(_c:number,l:number,r:number){return new FakeBuffer(l/r,r) as any;} }
const channel={id:'legacy-test',name:'Legacy',color:'#fff',instrumentType:'grand_piano',mixerTrackId:1,volume:0.8,pan:0,pitch:0,mute:false,solo:false,steps:[],notes:[],synthParams:{attack:0.01,decay:0.25,sustain:0.6,release:0.2,fmModulatorMultiplier:2,fmModulationIndex:150}} as any;
const note={id:'n',pitch:60,start:0,duration:1,velocity:0.8} as any;
describe('Phase 24 legacy instrument renderers',()=>{it('invokes every extracted renderer through InstrumentVoiceContext',()=>{const rs=[renderGrandPianoVoice,renderRhodesVoice,renderOrganVoice,renderPluckedGuitarVoice,renderStringsVoice,renderPizzicatoVoice,renderBrassVoice,renderMarimbaVoice,renderAcid303Voice,renderReeseBassVoice,render808SubVoice,renderSupersawVoice,renderAmbientPadVoice,renderVoxChoirVoice,renderChiptuneVoice,renderLegacyDrumVoice];for(const render of rs){const ctx=new FakeContext();render({channel,note,time:0,destination:{} as AudioNode,audioContext:ctx as any,voiceId:'test'});assert.ok(ctx.nodes.some(n=>n.startCalls>0));}});it('keeps shared renderer mappings explicit',()=>{const registry=createInstrumentRegistry({nylon_guitar:renderPluckedGuitarVoice,harpsichord:renderPluckedGuitarVoice,reese_bass:renderReeseBassVoice,slap_bass:renderReeseBassVoice},renderGrandPianoVoice);assert.equal(registry.get('nylon_guitar'),renderPluckedGuitarVoice);assert.equal(registry.get('harpsichord'),renderPluckedGuitarVoice);assert.equal(registry.get('reese_bass'),renderReeseBassVoice);assert.equal(registry.get('slap_bass'),renderReeseBassVoice);});});
